import {
  SiAstro,
  SiDocker,
  SiExpress,
  SiFramer,
  SiChakraui,
  SiGit,
  SiGithub,
  SiJavascript,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPrisma,
  SiReact,
  SiReactquery,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiVercel,
  SiRadixui,
} from "react-icons/si";

export const TECHNOLOGIES = [
  { name: "TypeScript", icon: SiTypescript, color: "#3178C6" },
  { name: "JavaScript", icon: SiJavascript, color: "#F7DF1E" },
  { name: "React", icon: SiReact, color: "#61DAFB" },
  { name: "TanStack Query", icon: SiReactquery, color: "#FF4154" },
  { name: "Next.js", icon: SiNextdotjs, color: "#FFFFFF" },
  { name: "MongoDB", icon: SiMongodb, color: "#47A248" },
  { name: "PostgreSQL", icon: SiPostgresql, color: "#4169E1" },
  { name: "Supabase", icon: SiSupabase, color: "#3FCF8E" },
  { name: "MySQL", icon: SiMysql, color: "#4479A1" },
  { name: "Astro", icon: SiAstro, color: "#FF5D01" },
  { name: "Git", icon: SiGit, color: "#F05032" },
  { name: "GitHub", icon: SiGithub, color: "#FFFFFF" },
  { name: "Node.js", icon: SiNodedotjs, color: "#339933" },
  { name: "Prisma", icon: SiPrisma, color: "#2D3748" },
  { name: "Radix UI", icon: SiRadixui, color: "#FFFFFF" },
  { name: "Framer Motion", icon: SiFramer, color: "#0055FF" },
  { name: "Docker", icon: SiDocker, color: "#2496ED" },
  { name: "Tailwind CSS", icon: SiTailwindcss, color: "#06B6D4" },
  { name: "Express.js", icon: SiExpress, color: "#FFFFFF" },
  { name: "Material UI", icon: SiMui, color: "#007FFF" },
  { name: "Chakra UI", icon: SiChakraui, color: "#319795" },
  { name: "Vercel", icon: SiVercel, color: "#000000" },
  { name: "Vite", icon: SiVite, color: "#FFFFFF" },
];
